language: go

go:
  - 1.9

sudo: false

git:
  depth: 10

branches:
  only:
    - master
env:
  global:
    - SOURCE_DIR="public"
    - BUILD_BRANCH="develop"
    - DEPLOY_BRANCH="master"

install:
  # Clean and don't fail
  - rm -rf public || exit 0
  # install hugo
  - go get -u -v github.com/spf13/hugo

# Build the website
script:
  - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

